name: Build pdf

on:
  push:
    branches:
      - '**'
    paths:
      - '*/scripts/statement.sh'
      - '*/statement/*.jpg'
      - '*/statement/DISABLE_AUTO_BUILD'
      - '*/statement/index.md'
      - '*/problem.json'
      - '*/subtasks.json'
      - 'template.tex'
      - 'cover.tex'
  workflow_dispatch:
    inputs:
      target:
        description: 'Problem labels to build (A-Z), "+" to merge pdfs'
        default: ''

jobs:
  problem-list:
    runs-on: self-hosted
    timeout-minutes: 3
    outputs:
      matrix: ${{ steps.problem-list.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Read problems
        id: problem-list
        run: |
          problems=$(cat .problems.json)
          echo "::set-output name=matrix::$problems"

  check-push:
    needs: [problem-list]
    if: ${{ github.event_name == 'push' && github.repository != 'TNFSH-Programming-Contest/tps-starter' }}
    runs-on: self-hosted
    timeout-minutes: 3
    strategy:
      matrix:
        problem: ${{ fromJson(needs.problem-list.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make flags dir
        run: |
          mkdir -p $RUNNER_TEMP/flags/
          touch $RUNNER_TEMP/flags/.keep

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: 'json'
          filters: |
            pdf:
              - p${{ matrix.problem }}/scripts/statement.sh
              - p${{ matrix.problem }}/statement/*.jpg
              - p${{ matrix.problem }}/statement/DISABLE_AUTO_BUILD
              - p${{ matrix.problem }}/statement/index.md
              - template.tex
            cover:
              - cover.tex

      - name: Set problem flag
        if: steps.changes.outputs.pdf == 'true' || (matrix.problem == 'A' && steps.changes.outputs.cover == 'true')
        run: |
          echo "${{ matrix.problem }}" > $RUNNER_TEMP/flags/${{ matrix.problem }}

      - name: Check changes in config
        run: |
          set +e

          git diff ${{ github.event.before }}..HEAD -U0 p${{ matrix.problem }}/problem.json | grep '"contest_name"\|"problem_label"\|"name"\|"title"\|"memory_limit"\|"time_limit"'
          if [ $? -eq 0 ]; then
            echo "${{ matrix.problem }}" > $RUNNER_TEMP/flags/${{ matrix.problem }}
          else
            echo "No changes in problem.json for pdf";
          fi

          git diff ${{ github.event.before }}..HEAD -U0 p${{ matrix.problem }}/subtasks.json | grep '"index"\|"score"\|"text"'
          if [ $? -eq 0 ]; then
            echo "${{ matrix.problem }}" > $RUNNER_TEMP/flags/${{ matrix.problem }}
          else
            echo "No changes in subtasks.json for pdf";
          fi

      - name: Remove flags if auto build disabled
        if: hashFiles(format('p{0}/statement/DISABLE_AUTO_BUILD', matrix.problem)) != ''
        run: |
          rm -f $RUNNER_TEMP/flags/${{ matrix.problem }}

      - name: Upload flags
        uses: actions/upload-artifact@v2
        with:
          name: flags
          path: ${{ runner.temp }}/flags/

  check-manually:
    needs: [problem-list]
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    timeout-minutes: 3
    strategy:
      matrix:
        problem: ${{ fromJson(needs.problem-list.outputs.matrix) }}

    steps:
      - name: Make flags dir
        run: |
          mkdir -p $RUNNER_TEMP/flags/
          touch $RUNNER_TEMP/flags/.keep

      - name: Set problem flag
        if: contains(github.event.inputs.target, matrix.problem)
        run: |
          echo "${{ matrix.problem }}" > $RUNNER_TEMP/flags/${{ matrix.problem }}

      - name: Upload flags
        uses: actions/upload-artifact@v2
        with:
          name: flags
          path: ${{ runner.temp }}/flags/

  check-post:
    needs: [check-push, check-manually]
    if: ${{ always() && github.repository != 'TNFSH-Programming-Contest/tps-starter' }}
    runs-on: self-hosted
    timeout-minutes: 3
    outputs:
      problems: ${{ steps.check-post.outputs.problems }}

    steps:
      - name: Download flags
        uses: actions/download-artifact@v2
        with:
          name: flags
          path: ${{ runner.temp }}/flags/

      - name: Set merge flag
        if: ${{ github.event_name == 'workflow_dispatch' && contains(github.event.inputs.target, '+') }}
        run: |
          echo "+" > $RUNNER_TEMP/flags/+

      - name: Check target
        id: check-post
        working-directory: ${{ runner.temp }}/flags/
        run: |
          probs=$(ls -m .)
          echo $probs
          echo "::set-output name=problems::$probs"

  build-pdf:
    needs: check-post
    if: always() && needs.check-post.outputs.problems != ''
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Download flags
        uses: actions/download-artifact@v2
        with:
          name: flags
          path: ${{ runner.temp }}/flags/

      - name: Install dependencies
        if: ${{ runner.name == 'Hosted Agent' || startsWith(runner.name, 'GitHub Actions') }}
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/ioi-2017/tps/master/online-installer/install.sh)"

          wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
          sudo dpkg -i pandoc-2.10.1-1-amd64.deb

          sudo apt-get install texlive-xetex

          sudo mkdir -p /usr/share/fonts/opentype/noto
          wget -nv https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJK-Regular.ttc.zip
          unzip NotoSansCJK-Regular.ttc.zip -d NotoSansCJK-Regular
          ls -al NotoSansCJK-Regular
          sudo cp NotoSansCJK-Regular/NotoSansCJK-Regular.ttc /usr/share/fonts/opentype/noto
          wget -nv https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJK-Bold.ttc.zip
          unzip NotoSansCJK-Bold.ttc.zip -d NotoSansCJK-Bold
          ls -al NotoSansCJK-Bold
          sudo cp NotoSansCJK-Bold/NotoSansCJK-Bold.ttc /usr/share/fonts/opentype/noto
          ls -al /usr/share/fonts/opentype/noto
          sudo fc-cache -f -v

          sudo apt-get install poppler-utils

      - name: Check environment
        working-directory: pA
        run: |
          lsb_release -a
          echo ""
          pandoc -v
          echo ""
          xetex -v
          echo ""
          tps || :;
          echo ""
          fc-list | grep "Noto Sans Mono CJK TC" || :;
          echo ""
          pdfunite -v

      - name: Build cover
        if: contains(needs.check-post.outputs.problems, 'A')
        run: |
          xelatex cover.tex

      - name: Build pdf
        run: |
          for prob in $(cat $RUNNER_TEMP/flags/*); do
            cd p${prob} && tps statement && cd ..
          done

      - name: Merge cover into pA
        if: contains(needs.check-post.outputs.problems, 'A')
        run: |
          pdfunite cover.pdf pA/statement/index.pdf pA/statement/index-with-cover.pdf
          rm pA/statement/index.pdf
          mv pA/statement/index-with-cover.pdf pA/statement/index.pdf

      - name: Merge pdfs
        if: contains(needs.check-post.outputs.problems, '+')
        run: |
          mkdir -p pA/attachments
          pdfunite pA/statement/index.pdf `# NEWPROBLEM` pA/attachments/problems.pdf
          git add pA/attachments/problems.pdf

      - name: Check diff
        run: |
          git diff --name-only

      - name: Commit pdf
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          for prob in $(cat $RUNNER_TEMP/flags/*); do
            git add p${prob}/statement/index.pdf
          done
          git pull
          git diff-index --quiet HEAD -- || git commit -m "Build pdfs"
          git push
