name: Build pdf

on:
  push:
    branches:
      - '**'
    paths:
      - '*/scripts/statement.sh'
      - '*/statement/*.jpg'
      - '*/statement/DISABLE_AUTO_BUILD'
      - '*/statement/index.md'
      - '*/problem.json'
      - '*/subtasks.json'
      - 'template.tex'
      - 'cover.tex'
  workflow_dispatch:
    inputs:
      problems:
        description: 'Problem labels to build (A-Z)'
        default: ''
      merge:
        description: 'Merge pdfs?'
        default: false
        type: boolean

jobs:
  run:
    uses: TNFSH-Programming-Contest/tps-actions/.github/workflows/build-pdf.yml@main
    with:
      problems: ${{ inputs.problems }}
      merge: ${{ inputs.merge && fromJson(inputs.merge) || false }}
